# Generated by Django 2.2.28 on 2025-09-13 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('MovieID', models.AutoField(primary_key=True, serialize=False)),
                ('MovieTitle', models.CharField(max_length=200)),
                ('Actor1Name', models.CharField(max_length=200)),
                ('Actor2Name', models.CharField(max_length=200)),
                ('DirectorName', models.CharField(max_length=100)),
                ('MovieGenre', models.CharField(max_length=100)),
                ('ReleaseYear', models.IntegerField()),
            ],
        ),
    ]
